name: Publish to GH packages

on:
  workflow_dispatch:

env:
  APEGROUPCI_USERNAME: ${{ secrets.APEGROUPCI_USERNAME }}
  APEGROUPCI_TOKEN: ${{ secrets.APEGROUPCI_TOKEN }}

jobs:
  publish:
    name: Publish to GH packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true

      - name: Build and publish package to GH registry
        run: ./gradlew --profile clean publishAllPublicationsToGitHubPackagesRepository

      - name: Upload profile reports
        uses: actions/upload-artifact@v4
        with:
          name: profile-report
          path: build/reports/profile/
          retention-days: 3
